### ISSUE TITLE
[Suggestion] Adding a config

### ISSUE THREAD

**Issue by ElvenWitchBirdy** [KawaiiBone/LethalCompanyRemnants#1]
I was wondering if we could get an auto-generated config of the spawned items and manually set spawn weights on them.

I mostly see modded store items as scrap laying around more often than vanilla. (In fact, in all of my sight-seeing test runs, I never saw any vanilla item laying around). It gets a bit too OP when you can find rocket launchers from LethalThings around in every 2-3 runs.

**Comment by KawaiiBone** [comment]
Thank you for the suggestion.
This is a fun idea, that I will definitely work on  in the near future.

The issue of vanilla items barely or never spawning could be because, the rarity of the item is measured by the amount of credits it costs when you buy it from the store. The more expensive an item the less chance of spawning that item, the rarity now ranges from 1% to 10%.
Could also be that there is a bug in my mod or a compatibility issue with other mods.
Either way i will look into this issue and try to fix it.
Thank you for making me aware of the issue.

**Comment by Fl4sHNoX** [comment]
+1

An auto-generated config of the spawned items would actually be a great way to fix some issues in the way some mods handle items! (cf. [Items "disabled" from being able to be purchased in the store from other mods can still be found in moons](https://github.com/KawaiiBone/LethalCompanyRemnants/issues/3)).

It would also be very neat to be able to disable some items from mods that still allow them to be purchased in the store but you don't want to have spawning on the floor for whatever reason.

**Comment by KawaiiBone** [comment]
Since there is a config now, are there any more suggestions for the config?
Like adding features, changing features or making things more clear.

**Comment by Fl4sHNoX** [comment]
> Since there is a config now, are there any more suggestions for the config? Like adding features, changing features or making things more clear.

So far I don't have any pressing suggestions coming to mind, but thank you very much for your work and adding these features to your great mod! ❤️
