### ISSUE TITLE
[Feature Request] Item spawn limit, rarity, and additional item spawn chance.

### ISSUE THREAD

**Issue by Sourceshard** [KawaiiBone/LethalCompanyRemnants#14]
Currently, you can set a floating value modifier that will spawn several items or an item of the listed value. I would like to have a few items spawn so I have set the value low. However, this leads to only items like flashlights and TZP generating. I would like to be able to set a maximum amount of items to spawn.

For example, if I wanted only one item to spawn. I would like to set the pool of items, make the more expensive items rare, and have one randomly picked from the list. If I were to have more than one item spawn I would like to set different generation weights.

1st item: 100% spawn chance. - Normal chances.
2nd item: 30% spawn chance. - Lower chance of high-value items.
3rd item: 5% chance. - No chance of high-value items.

Having this percentage value for additional items be adjustable in the config would be great.

**Comment by KawaiiBone** [comment]
This mod already have some parts similar to what you have asked.
In the config you can tweak the rarity of items between two numbers and between those numbers the rarity will be calculated in relative to the credits cost of that item.
So an expensive item will have a less chance of spawning then an item like a flashlight. 
The way it calculates the rarity by credit cost is by using a minimum and maximum value, the minimum is 1(not in config) and the default maximum is 400 which you can edit in the config in the section of _Other_.
Although it is not recommended to tweak this value since 400 is the highest cost of a shop item I think.

If you don't want certain items to be spawned as remnant items you can change that in the config in the section called _Remnants_.

For this mod I focused more on chance of spawning remnant items per moon, since that is a feature from the game itself and from LethalLib. Separately changing an item spawn chance would mean that it would be all the same on all moons, otherwise it would immensely clutter up the config.
I do not know If that is a feature that I add without making the config clutter up more.

**Comment by apeng0907** [comment]
i think the significance of spawning remnant items per moon is very small，i hope change an item spawn chance

**Comment by Sourceshard** [comment]
I find this very hard to understand. XD
![image](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/37197624/2edf7644-46ef-4519-ae14-c3c47cb72653)

**Comment by Sourceshard** [comment]
I use Late Game Upgrades and mods that add items to the store. I believe for my game personally the value can go up to 900 credits. I want all items to be achievable but only like 1 per remnant spawn.

**Comment by apeng0907** [comment]
Yes, I set Min residual item rarity to 100, [Remnants] only Shovel is true, but the  shovel spawn is still very small

**Comment by apeng0907** [comment]
> 
> 如果您不希望某些物品作为残余物品生成，您可以在名为_“残余_”部分的配置中进行更改。
> 
> 对于这个模组，我更关注每个月亮生成剩余物品的几率，因为这是游戏本身和 LethalLib 的一个功能。单独更改物品的生成几率意味着它在所有卫星上都是一样的，否则会极大地混乱配置。我不知道这是否是我添加的功能，而不会使配置更加混乱。



> This mod already have some parts similar to what you have asked. In the config you can tweak the rarity of items between two numbers and between those numbers the rarity will be calculated in relative to the credits cost of that item. So an expensive item will have a less chance of spawning then an item like a flashlight. The way it calculates the rarity by credit cost is by using a minimum and maximum value, the minimum is 1(not in config) and the default maximum is 400 which you can edit in the config in the section of _Other_. Although it is not recommended to tweak this value since 400 is the highest cost of a shop item I think.
> 
> If you don't want certain items to be spawned as remnant items you can change that in the config in the section called _Remnants_.
> 
> For this mod I focused more on chance of spawning remnant items per moon, since that is a feature from the game itself and from LethalLib. Separately changing an item spawn chance would mean that it would be all the same on all moons, otherwise it would immensely clutter up the config. I do not know If that is a feature that I add without making the config clutter up more.

How can I set up to spawn more shovels internally？

**Comment by KawaiiBone** [comment]
Thank you for the responses,

The Remnants mod uses the way how Lethal Company spawns its scrap rather than another way. (Except for body spawning)
So the reason why some remnant items spawn twice, is the same reason why you see two bolts in the factory.
Because all the scrap and the remnant items are in the same list and get randomly chosen, those with a higher spawn chance will have more of a chance of being spawned than those with a low spawn chance.
I cannot control how many remnant items will spawn in the level apart from influencing its spawn chance, which you can change in the config.
So if you have a lot of mods that gives the Remnant mod a lot of remnant items, then you would see more remnant items.
Depending also on how much spawn chance you gave them in the config.

For the config part that is confusing, I shall rewrite the info on it to make it more clear. 
With what you want to achieve, you could then set that config value to 900 and set the min rarity to 1% so the chance of such item will spawn is very unlikely. But the value also has other uses for the default is 400 which means any item 400 or above will be automatically seen as very rare, so the lowest chance to spawn. This is handy if you want to have many items that cost x or more to spawn very rarely. 

The shovel issue, I have done the same as you did and disabled all remnant items but the shovel and set the spawn chance at 100%, I tested it 5 times and saw always that one or 2 shovels have spawned.
We can conclude that the shovel does spawn, which I can understand the frustration about it if you want more than 2 shovels spawned in the factory. 
So the conclusion is that you have already set up the max chance to spawn the shovel, there is nothing more that this mod can increase.

I do understand the frustration of not controlling the spawning fully of the remnant items.
All that I can say is that when I have some free time for it, I can start taking a look in finding a way to make this still work.
But I cannot be certain if that will happen.

**Comment by KawaiiBone** [comment]
The newest patch (1.3) has separate spawning now with remnant items.
Normally most of the features request here, are added.
