### ISSUE TITLE
[Bug/Feature Request] Reserved Slots Compatibility

### ISSUE THREAD

**Issue by Sourceshard** [KawaiiBone/LethalCompanyRemnants#18]
I am not sure if this is a bug or by design. 

The reserved slots mod has slots that are meant for different types of tools. Items spawned as scrap by Remnants do not seem to occupy these slots. 

However, another mod called Abandoned Company Assets is capable of having their items in these slots. Their items also count as scrap.

https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedItemSlotCore/
https://thunderstore.io/c/lethal-company/p/FlipMods/
https://thunderstore.io/c/lethal-company/p/Sconeys/abandonedcompanyassets/

**Comment by KawaiiBone** [comment]
I have tested this issue was well, and have notices if you download the mod ReservedFlashlightSlot v2.0.3 by FlipMods, it does work for the flashlights that are spawned as remnants.
But I think that this is not the specific issue.
Could you elaborate a bit more about this issue?

Thank you for reporting the issue.

**Comment by Sourceshard** [comment]
In this case I am referring to all of the slots. Walkie, Weapon, Ammo, Key, Utility, Spray Paint. 

For example in my utility slot, I have many items. 

These are the Default Settings.
"Extension ladder", "Lockpicker", "Jetpack", "Stun grenade", "Homemade flashbang", "TZP-Inhalant", "Radar-booster", "Remote Radar", "Utility Belt", "Hacking Tool", "Pinger", "Portable Tele", "Advanced Portable Tele", "Peeper", "Medkit", "Binoculars", "Mapper", "Toothpaste"

I have added these.
Emergency Flare,Flare Gun,Enemies Scanner,Walkman,Geiger Counter,Whistle,Abandoned TZP-Inhalant,OxyBoost,Pintoboy,PintoBoy,Emergency Die,Chronos,The Saint,The Sacrificer,The Gambler,Rusty,MP3 player,Polaroid


As long as I specify the name of an item it should enter the slot and be used. However, Remnant Items that share the same name do not. 

For example, the spray paint can that I reported with a stretched image did not enter the spray paint slot.

**Comment by KawaiiBone** [comment]
This seems to be a problem related to typing in the name incorrectly.
I have tested this thoroughly and only the remnant items and normal items that I misspelled did not go in the utility slot.
Do take note if you are using the console and copy pasting the names of the remnant items into the ReservedItemSlotCore config, then some items will not work because items in Lethal Company have two kinds of names for each item, the item object name and the variable itemName in the item object.
(This can part can become confusing)
A good example is: object item name for walkie talkie is called _WalkieTalkie_ and the itemName variable in the item object is called _Walkie-talkie_.
The ReservedItemSlotCore mod uses the latter, and the Remnants mod uses both, but only outputs the first one in the console to easily spot mistakes for me and people playing this mod.

I can of course use the latter one to make it easier for you, that will come through then on the next update of this mod.

Another example, all of these items work here apart from LockPicker because I misspelled it.
![Screenshot 2024-04-18 162652](https://github.com/KawaiiBone/LethalCompanyRemnants/assets/159925618/5a145f5e-ddf8-4fd2-b759-618b4b77b282)


If this issue still persists, then it could be another problem of compatibility or something else.
When that happens and you find an error in the console while playing the game, do please take a screenshot of it.
