### ISSUE TITLE
[Feature Request] Be able to adds scrap items in the list of Remnants

### ISSUE THREAD

**Issue by IAmSympathy** [KawaiiBone/LethalCompanyRemnants#20]
Would let us be able to add any items as remnants,

The point would be for mods that adds usefull scrap like Abandoned Company Assets (adds store items with malfunctions like abandonned flashlight, abandonned walkie-talkie), to add them to the list of remnants so they can spawn next to bodies.
The way this could work could be by entering the scrap name in a text field in the config.

Since I play with 100% chance for body to spawn next to a remnant, that would be usefull and more immersive.

**Comment by KawaiiBone** [comment]
Normally, the Remnants mod is compatible with other mods having store items and registering them as remnant items.
But the way I understand, it does not work with Abandoned Company Assets mod?
If that is the case, I will take a look at this issue and see If I can find a possible fix for it.

Thank you for reporting the issue.

**Comment by KawaiiBone** [comment]
This seems because the items are already scrap and the Remnant items do not register scrap.
So like you suggested, I could add a config feature where you can add the item name for it, to force add it to the remnants list.
If it works you will see then the item in the config section called _Remnants_.
Do take in mind that you would need to type in the name perfectly, otherwise it would not work.

This feature will be added probably on the next update.
