### ISSUE TITLE
[Feature Request] Be able to disable the random suit feature

### ISSUE THREAD

**Issue by IAmSympathy** [KawaiiBone/LethalCompanyRemnants#21]
Option 1: Desactivate the random suits feature so only the default one (orange) can be chosen for dead bodies.

Option 2: Be able to blacklist certain suits via the config file, so typing the suits name in a text filed would prevent it to be chosen for a dead body.

**Comment by IAmSympathy** [comment]
Also, sorry if I'm sort of spamming with the feature request/bug reports, since you're not on the LC Modding Discord, there's no other way to report/suggest features.

**Comment by KawaiiBone** [comment]
Those are fun ideas indeed, I will sure work on adding those features.
What will probably happen, is that you will see a new section in the config and be able to disable these suits.

Thank you for the feature request

**Comment by KawaiiBone** [comment]
> Also, sorry if I'm sort of spamming with the feature request/bug reports, since you're not on the LC Modding Discord, there's no other way to report/suggest features.

No need to feel sorry, I put it on this site to be used this way.
Normally I have a thread in the [Unofficial Lethal Company discord](https://discord.com/invite/nYcQFEpXfU) in the section _Scrapyard_ and in the forum _Mod-releases_, There you will be able to find me to.
The main reason I am not on the LC Modding Discord is because I have no idea how to get a modding role there, whenever I click the role Gameplay It keeps declining me.

**Comment by IAmSympathy** [comment]
In order to get the modding role all you have to do is post your mod in mod-releases, a moderator will then manually give you the modder role.

And thanks for listening to all my feedbacks!

**Comment by KawaiiBone** [comment]
Thank you for telling me how to set up in the LC Modding Discord.
I have added the suit feature and thus now I will close this issue.
