### ISSUE TITLE
[Nitpick/Suggestion] Corpse text

### ISSUE THREAD

**Issue by MathiusXII** [KawaiiBone/LethalCompanyRemnants#29]
1: For the regular corpse, the death type is properly capitalized as "Unknown", while all other bodies are all lowercase. ("head burst", "coil", "webbed")

2: The name is lowercase "unknown". I'd prefer it be capitalized. (I also think it'd be cool if name was "Employee 13-4496" (random #s) instead of "Unknown")

3: The death types are inconsistent with actual death types. According to the wiki, "webbed" and "coil" are "Mauling" and "head burst" is "Unknown". Maybe the default body's unknown death could be "Inconclusive"?

No pressure to "fix" any of this. I'm just being nitpicky.

**Comment by KawaiiBone** [comment]
These are some nice ideas, for some reason I keep typing something wrong with the word unknown. 
Ill be sure to put the renaming bodies to there proper name in my backlog.

For the random name instead of "Unknown", is there a reason why you said "Employee 13-4496"?
I understand the employee part and the random numbers seems to be cool.
Yet I don't understand the specific reason for the numbering like that in the scope of Lethal Company.
Because I have not seen any employee numbered like that, unless I have missed some lore or gameplay.

Thank you for the feedback.

**Comment by MathiusXII** [comment]
I'm not aware of any official employee naming/numbering convention so I just made one up.
If there is one, I'd use that.

**Comment by KawaiiBone** [comment]
I have added the feedback for naming the deaths correctly using the Lethal Company wiki as reference.
Sadly I won't be changing the id names of the bodies.
This is because there is already a lot happening when spawning a body and adding this specific feature would make it very difficult to save, since the body already saves the suit.
