### ISSUE TITLE
[Request] option to use other suits even when locked

### ISSUE THREAD

**Issue by JohnMetroid** [KawaiiBone/LethalCompanyRemnants#30]
hey there, it would be great to get an option to use the extra suits on remnant corpses even when the player doesn't have the suits unlocked.  It seems that by default only the unlocked suits are selected from, so corpses are always orange until you buy new suits.

It would also be great if there was an option to similarly allow remnant corpses to use MoreSuits suits.

thanks for the consideration

**Comment by KawaiiBone** [comment]
I have only recently found this out, but this is actually a bug if you use bodies as scrap.
It seems that only the default suits are used to spawn them.
Normally it should be fixed in the next update.

About the mod compatibility with suits, I am also working on this part now, especially for the MoreSuits mod.

The features and issues should be fixed and done on the next update.
Thank you for the feedback.
