### ISSUE TITLE
error or fault

### ISSUE THREAD

**Issue by RiseKennet** [KawaiiBone/LethalCompanyRemnants#31]
hi!
I'm playing with a group of my friends and I keep getting the same error

we find any forgotten items and when we take them in our hands we can't throw them away anymore. it's also impossible to leave the complex with these items

if the player is teleported to the ship he will no longer be able to pick things up, send the ship into orbit or open doors

maybe this problem is only us but even updating your mod did not help to solve this problem

**Comment by KawaiiBone** [comment]
This may be a incompatibility with another mod that I don't know of.
Because the most recent versions of the Remnants mod has no issues like that.

Are you playing also with other mods?
If so could you send me the profile code for it?
Also if you have a log of the game would also help to find the bug.

Thank you for reporting the issue.

**Comment by RiseKennet** [comment]
Here's the code we used for the game:

018f8c38-c01e-4a7d-d722-127d80e81838

**Comment by KawaiiBone** [comment]
This seems to be an incompatibility issue with the mod Lategame_Upgrades.
It seems that the cleaning up of remnant items does not occur when this mod is active.
Which causes the issues.
I will take a closer look If I can fix this issue on my end.
This issue seems only to happen on disconnect if there are remnant items still either on the ship or on the map.

Thank you for reporting the bug.

**Comment by KawaiiBone** [comment]
I found a way to fix this issue.
This issue will be fixed on the next update of this mod.

**Comment by KawaiiBone** [comment]
This issue is fixed on the latest update (1.3.2) or earlier.

If there is still an issue around it, you create a new issue here on GitHub.
