### ISSUE TITLE
Not working on Artifice

### ISSUE THREAD

**Issue by YKoF-CALm** [KawaiiBone/LethalCompanyRemnants#34]
I don't think this is intentional, but remnant scrap does not spawn on Artifice at all (config is default config).

**Comment by KawaiiBone** [comment]
The bug seems to be that I did not update the risk levels along the new patch of Lethal Company. 
Because Artifice risk level is s++ and I only measure to s+, by default if it can't find the risk level and it will automatically puts the remnant spawn modifier to 0 causing no items to spawn.
This bug will be patched in the next update of this mod.

Thank you for reporting the bug.

**Comment by KawaiiBone** [comment]
This issue is fixed on the latest update (1.3.2).

If there is still an issue around it, you create a new issue here on GitHub.
