### ISSUE TITLE
Remnant spawns items regardless of settings

### ISSUE THREAD

**Issue by xXShepardXx** [KawaiiBone/LethalCompanyRemnants#37]
Hi, I found those 2 issues with Remants:

 1. Items spawn regardless of them being set to -1 in config (I tested it also by installing only remnants with dependencies in a separate profile)
 2. there is some error when remnants is installed with this one particular skin:
https://thunderstore.io/c/lethal-company/p/Smtony/LuigiModel/

![Luigi error with remnant](https://github.com/user-attachments/assets/400e652d-a6f4-4165-8874-36df2150bf6e)

game version:
v56
remnant version:
v1.3.4

**Comment by KawaiiBone** [comment]
The -1 in the config setting still spawns the item is intended, since it spawns the item with the rarity in relative of its cost in the shop.
If you want to not spawn an item you should put the value to 0.
The problem seems to be from the Luigi's Mansion skin, I did not took in mind a preventive measure.
This issue will be fixed on the next update, but sadly the Luigi's Mansion skin will not be seen on the dead bodies from this mod.
Due to the skin having an **" ' "** in its name, which causes some problem in programming.

Thank you for the issue report.

**Comment by KawaiiBone** [comment]
This issue should be fixed now on the current version, I will close this issue in a couple of weeks unless it is still present.
