### ISSUE TITLE
[Bug (?)] Remnant spawn list ignores spawn weights

### ISSUE THREAD

**Issue by JohnMetroid** [KawaiiBone/LethalCompanyRemnants#38]
Hey there,

I was doing another pass on Remnant items.  I went through and set remnant spawn weights for the individual items (e.g. 100 for flashlight; 50 for pro-flashlight; 25 for shovel, etc).  When going through a few dungeons and checking the drops, it seems like these weights are disregarded and it's weighing the items the same.

Thanks

**Comment by KawaiiBone** [comment]
Hi,

The reason for that is in the config called the _General Rarity_ in section _General_, these values clamp the weights of the items. I would suggest putting the default values from 5%-25% to 1%-100%.

I hope this helps.

**Comment by JohnMetroid** [comment]
I guess I'm confused at how all of this works together.  Wouldn't it make more sense to simply allow me to set a weight for each individual piece of equipment?  Then when picking which piece of equipment gets dropped as a remnant item, pick the item based on the weights supplied in the "Remnants" section?  I don't understand how a specific percentage specification would even make sense on a list of equipment of indeterminate size.

edit: Based on the current setup of Remnant spawning, I suppose my main question is: What happens when the sum of my provided Remnant weights exceeds 100?  Are the weights properly handled in a case where the total Remnants spawn weights is, for instance, 600 (e.g. Pro-Flashlight = 100 would have a 100/600 drop rate -- or 16.67% effective chance)?  In which case, it would be **much** clearer if the "General Rarity" section wasn't referred to as percentages (because it immediately falls apart in any case where the total weights aren't 100).

Thanks

**Comment by KawaiiBone** [comment]
All of the remnant items get clamped between 1 and 100 (they cannot exceed 100 or get lower then 1), this is the percentage chance that it will spawn. The _General rarity_ is there to clamp the spawn chance of all the moons and if you want it to be specific per moon, you can change the config feature _Use level specific rarities_. The reasons why it exist is so you can have more control over your spawning per moon, this mainly exist for the older version of spawning remnant items. (Legacy spawning)
Because in that older version (it spawns along the scrap items) you have less control of how many remnant items you spawn and you don't want to only spawn remnant items and have no scrap items on the moon.

Thankfully the new spawning does not interfere with the scrap spawning, so the _General rarity_ becomes a bit obsolete. But it can still be very handy for updating the spawn chance per moon/level. (the config feature _Use level specific rarities_) 

So you don't need to worry about adding the spawn chance to 200, since it will just clamp to 100. The calculation will go like this: If the _General Rarity_ is 5%-25% and your remnant item rarity is 50% then it will have a 15% rarity.
For the new version of spawning this means not a lot, unless you have an extreme low or high rarity. Which means that those remnant items have a higher or lower chance spawning, this is why with the default setting you can still see 2 Zap guns. 
For the legacy spawning this means more, since its rarity will be chosen among scrap items.

I do understand that the current default is more set for the Legacy spawning, so I understand the confusion for this.

This does make more sense?

**Comment by JohnMetroid** [comment]
>This does make more sense?

Honestly no, I'm still rather confused.  I feel like the continued confusion highlights why calling it a percent while referring to it as a weight is extremely problematic. Can you answer my question from my last post?

>What happens when the sum of my provided Remnant weights exceeds 100? Are the weights properly handled in a case where the total Remnants spawn weights is, for instance, 600 (e.g. Pro-Flashlight = 100 would have a 100/600 drop rate -- or 16.67% effective chance)?

**Comment by KawaiiBone** [comment]
I'm sorry to hear that, 

See it more that the weights, rarity spawn chance is all the same in this context.

The sum of a provided remnant item weight cannot exceed 100 nor can it get lowered then 1. All of the remnant items are between 1 and 100 and are put in a container where they are randomly picked, the higher the number the higher the chance they get picked. The chance of spawning a remnant item is determent by the amount of different remnant items, their weight and the amount of duplicates it can have.

So the sum of my provided Remnant weight does not matter in this context if that makes sense.

**Comment by KawaiiBone** [comment]
> What happens when the sum of my provided Remnant weights exceeds 100? Are the weights properly handled in a case where the total Remnants spawn weights is, for instance, 600 (e.g. Pro-Flashlight = 100 would have a 100/600 drop rate -- or 16.67% effective chance)?

To give a more clear answer, it would be 16.67%. But only if that item gets first chosen and it would only matter if you would only spawn very few remnant items. In the default you would spawn around 15 remnant items per moon (depending on their risk level), and there it would at least 2-4 flashlights and 1-2 zap guns. Because the default has a maximum of 4 duplicates of one item.

**Comment by JohnMetroid** [comment]
Ok, so functionally speaking the current system (non-legacy spawning) should work essentially identically to the current Lethal Company weighting system -- with the caveat that weights are required to be within [1,100].  I'll do some more testing after I revise the config and make sure the drops seem to be consistent with this.

Thanks for the help.

**Comment by JohnMetroid** [comment]
I regret to inform you that spawning does not work as you have described.  To test this, I set max remnant spawns per equipment type to 15 (the internal maximum) and set each moon to 30 remnant drops.  I then set the weights as follows: 100 for flashlight, 100 for pro-flashlight, and 1 for ~a dozen other equipment.

The expectation being that on average, remnants will spawn almost-exclusively with flashlights and pro-flashlights to test the spawning system.  Instead, the drops are apparently completely randomized.

I have confirmed this with repeated drops on a moon with the Sewer interior to make locating large numbers of bodies very easy.

![image](https://github.com/user-attachments/assets/aebbeab2-94d8-4ea4-97b9-6820cd580b91)

edit: attached test config before I revert it (converted to text to allow github upload)

[Remnants.txt](https://github.com/user-attachments/files/16504318/Remnants.txt)

**Comment by KawaiiBone** [comment]
You are right indeed, there is something wrong in my code for picking a random remnant item.

This issue shall be fixed on the next update.
Thank you for putting so much effort in this.

**Comment by KawaiiBone** [comment]
This issue should be fixed now on the current version, I will close this issue in a couple of weeks unless it is still present.

**Comment by JohnMetroid** [comment]
thanks for fixing it so quickly!

I'll do my best to run a quick check in the next night or two and close this out on my end

cheers

**Comment by JohnMetroid** [comment]
happy to report that a similar test config has been successfully observed to drop remnant items as expected with the updated Remnant version.

thanks so much

![image](https://github.com/user-attachments/assets/bbe35bfd-3c53-4bff-b81d-db4c978780b5)
![image](https://github.com/user-attachments/assets/555e32cc-57dd-43e4-972d-32fe6304e0d8)
