### ISSUE TITLE
[Request] Set rarity of corpse types

### ISSUE THREAD

**Issue by MathiusXII** [KawaiiBone/LethalCompanyRemnants#41]
I'd like to make webbed bodies less common

**Comment by KawaiiBone** [comment]
The type of bodies you see per level is determent by the monsters that will spawn and their rarity.
The higher the chance that a monster will spawn, the higher that body might spawn as well.
This is to give the player a tip to what kind of monster might be lurking around in that level.
So that is probably why you would see a lot more webbed bodies on a moon like Experimentation. 

This mod has kind of ended in content and will only update to work on the newer versions, bug fixes and compatibility issues.
