### ISSUE TITLE
Asking for compatibility with Piggys Variety Mod By Piggy

### ISSUE THREAD

**Issue by LoneMekkAzulf40K** [KawaiiBone/LethalCompanyRemnants#46]
Hello, first i wanted to tell you that your mod is really cool and i like to use it on most of my packs for challenges that me and my friends are doing weekly. 😄

I noticed that even when i configure Piggys Variety Mod to add Revolvers/Rifles and their respective ammunitions on the store, Remnants sadly seems to not be able to detect any of those, or at least, it does not add them on the configuration file under the "Remnants" category. (While items from LethalThings By Evaisa are properly added.)
(Modpack code : 0193b177-617a-fc01-40e0-a3dfabe84de8)

I am not 100% sure why is that and who to ask first, which is why i came here for asking if it's possible to make it work on the first place ?

Have a great day/night and thanks for reading/replying 😄

**Comment by KawaiiBone** [comment]
Thank you, that is nice to hear. :)

The reason for why this happens is that the Remnants mod only gets store items rather then scrap items. 
The weapons and ammo's are both items for the store but also counted as scrap, which means that it does not get converted into a remnant item. 

Sadly that means I can't easily change it since that would mean a lot of other items could get registered to become remnant items and could create a lot of errors. 

I do think that is okay since the Piggys Variety Mod can spawn those items on its own I would assume.

Hope this helps!

**Comment by LoneMekkAzulf40K** [comment]
Okay, thanks for the explanation, i liked the fact that your mod spawed remnants items outside of the initial scrap count so i hoped it could work somehow 🤷‍♂️

I will manage this in another way then 😅
